import{a as S,S as E,i as a}from"./assets/vendor-DxEWe7lX.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="47540419-36cc7af233202b3a7b66af182",M="https://pixabay.com/api/";async function m(e,r=1){try{return(await S.get(M,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(s){return console.error("Помилка завантаження:",s),{hits:[]}}}const y=document.querySelector(".gallery"),u=document.querySelector(".loader"),g=document.getElementById("load-more");let h;function p(e){const r=e.map(({webformatURL:s,largeImageURL:c,tags:t,likes:o,views:i,comments:$,downloads:B})=>`<li class="gallery-item">
      <a href="${c}" class="gallery-link">
        <img src="${s}" alt="${t}" loading="lazy">
      </a>
      <div class="image-info">
        <p>❤️ ${o}</p>
        <p>👁️ ${i}</p>
        <p>💬 ${$}</p>
        <p>⬇️ ${B}</p>
      </div>
    </li>`).join("");y.insertAdjacentHTML("beforeend",r),h?h.refresh():h=new E(".gallery a")}function P(){y.innerHTML=""}function L(){u.style.display="block",u.classList.add("visible")}function b(){u.style.display="none",u.classList.remove("visible")}function v(){g.style.display="block"}function l(){g.style.display="none"}const H=document.querySelector(".form"),I=document.getElementById("load-more");let d="",f=1,n=0;H.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.target.elements["search-text"].value.trim(),f=1,n=0,!d)return a.error({message:"Будь ласка, введіть запит!"});P(),l(),L();try{const r=await m(d,f);b(),!r||!r.hits||r.hits.length===0?(a.warning({message:"Sorry, there are no images matching your search query. Please try again!"}),l()):(p(r.hits),n=r.hits.length,n<r.totalHits?v():(l(),a.info({message:"You've reached the end of search results."})))}catch(r){w(r)}});I.addEventListener("click",async()=>{f++,L();try{const e=await m(d,f);b(),!e||!e.hits||e.hits.length===0?(l(),a.info({message:"You've reached the end of search results."})):(p(e.hits),n+=e.hits.length,console.log(`Завантажено: ${n}, Всього доступно: ${e.totalHits}`),n>=e.totalHits?(l(),a.info({message:"You've reached the end of search results."})):v(),window.scrollBy({top:document.querySelector(".gallery").offsetHeight*2,behavior:"smooth"}))}catch(e){w(e)}});function w(e){console.error("Помилка отримання зображень:",e.message||e),a.error({message:"Не вдалося завантажити зображення!"})}
//# sourceMappingURL=index.js.map
