import{a as u,S as f,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const d="47540419-36cc7af233202b3a7b66af182",m="https://pixabay.com/api/",y=u.create({baseURL:m,params:{key:d,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});function g(e){return console.error("Помилка отримання зображень:",e.message||e),[]}async function p(e,s=1){var o;try{const r=await y.get("",{params:{q:e,page:s}});return console.log(r.data),(o=r.data.hits)!=null&&o.length||console.warn(`Немає результатів для запиту: ${e}`),r.data.hits}catch(r){return console.error("Помилка завантаження:",r),alert("Не вдалося завантажити зображення"),g(r)}}let l;function h(e){const s=document.querySelector(".gallery");if(!s){console.error("Елемент .gallery не знайдено!");return}i();const o=e.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}" class="gallery-link">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
        </a>
        <div class="image-info">
          <p>❤️ ${r.likes}</p>
          <p>👁️ ${r.views}</p>
          <p>💬 ${r.comments}</p>
          <p>⬇️ ${r.downloads}</p>
        </div>
      </li>
    `).join("");s.innerHTML=o,l?l.refresh():l=new f(".gallery a")}function L(){const e=document.querySelector(".loader");e?e.classList.remove("visible"):console.error("Елемент .loader не знайдено!")}function b(){const e=document.querySelector(".loader");e?e.classList.add("visible"):console.error("Елемент .loader не знайдено!")}function i(){const e=document.querySelector(".gallery");e?e.querySelectorAll(".gallery-item").forEach(o=>o.remove()):console.error("Елемент .gallery не знайдено!")}const v=document.querySelector(".form");v.addEventListener("submit",async e=>{e.preventDefault();const s=e.target.elements["search-text"].value.trim();if(!s)return c.error({message:"Будь ласка, введіть запит!"});i(),b();try{const{hits:o}=await p(s);o!=null&&o.length?(console.log("Отримані зображення:",o),h(o)):c.warning({message:"Sorry, there are no images matching your search query. Please try again!"})}catch(o){S(o)}L()});function S(e){console.error("Помилка отримання зображень:",e.message||e),c.error({message:"Не вдалося завантажити зображення!"})}
//# sourceMappingURL=index.js.map
