import{a as B,S as E,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const S="47540419-36cc7af233202b3a7b66af182",$="https://pixabay.com/api/";async function u(e,r=1){try{return(await B.get($,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(s){return console.error("Помилка завантаження:",s),{hits:[]}}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.getElementById("load-more");let d;function p(e){const r=e.map(({webformatURL:s,largeImageURL:a,tags:t,likes:o,views:n,comments:v,downloads:w})=>`<li class="gallery-item">
      <a href="${a}" class="gallery-link">
        <img src="${s}" alt="${t}" loading="lazy">
      </a>
      <div class="image-info">
        <p>❤️ ${o}</p>
        <p>👁️ ${n}</p>
        <p>💬 ${v}</p>
        <p>⬇️ ${w}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),d?d.refresh():d=new E(".gallery a")}function M(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function P(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const q=document.querySelector(".form"),O=document.getElementById("load-more");let i="",l=1;q.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.elements["search-text"].value.trim(),l=1,!i)return c.error({message:"Будь ласка, введіть запит!"});M(),L(),y();try{const r=await u(i,l);g(),!r||!r.hits||r.hits.length===0?c.warning({message:"Sorry, there are no images matching your search query. Please try again!"}):(p(r.hits),P())}catch(r){b(r)}});O.addEventListener("click",async()=>{l++,y();try{const e=await u(i,l);g(),!e||!e.hits||e.hits.length===0?(L(),c.info({message:"You've reached the end of search results."})):p(e.hits)}catch(e){b(e)}});function b(e){console.error("Помилка отримання зображень:",e.message||e),c.error({message:"Не вдалося завантажити зображення!"})}
//# sourceMappingURL=index.js.map
